services:
  - type: web
    name: yt-downloader
    runtime: node
    buildCommand: npm install && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp && chmod 755 ./yt-dlp
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
    autoDeploy: true
